apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stutorial-deployment
  namespace: k8tutorialnamespace
  labels:
    app: k8stutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8stutorial
  template:
    metadata:
      labels:
        app: k8stutorial
    spec:
      containers:
        - name: k8tutorial-container
          image: azizkale/k8tutorial:latest
          ports:
            - containerPort: 3000
