apiVersion: v1
kind: Service
metadata:
  name: k8stutorial-service
  namespace: k8tutorialnamespace
spec:
  type: LoadBalancer
  selector:
    app: k8stutorial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
