name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azizkale/k8tutorial:latest

      - name: Set up K8s
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Decode KUBE_CONFIG_DATA and write to file
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/k8stutorial-deployment k8tutorial-container=azizkale/k8tutorial:latest --namespace k8tutorialnamespace

      - name: Restart Kubernetes Deployment
        run: |
          kubectl rollout restart deployment k8stutorial-deployment --namespace k8tutorialnamespace
